spring:
  application:
    name: gateway
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      maxRequestSize: 1000MB
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
#      routes:
#        - id: service-auth
#          uri: lb://service-auth
#          predicates:
#            - Path=/auth/**
#          filters:
#            - StripPrefix=1
#        - id: service-file
#          uri: lb://service-file
#          predicates:
#            - Path=/file/**
#          filters:
#            - StripPrefix=1
#system
server:
  port: 2000
  tomcat:
    basedir: /data/verify/temp/

#logback
logging:
  config: classpath:config/logback-spring.xml



