spring:
  datasource:
    url: jdbc:mysql://localhost:3306/verify?characterEncoding=utf8&allowMultiQueries=true&useSSL=false&autoReconnect=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  instance:
    prefer-ip-address: true
    instance-id: service-file
    # 每隔5s发送一次心跳
    lease-renewal-interval-in-seconds: 5
    # 告知服务端10秒还未收到心跳的话，就将该服务移除列表
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/

file:
  path: D:/data/file

host:
  uri: http://localhost:${server.port}