spring:
  datasource:
    url: jdbc:mysql://localhost:3306/verify?characterEncoding=utf8&allowMultiQueries=true&useSSL=false&autoReconnect=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  instance:
    prefer-ip-address: true
    instance-id: service-file
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/

file:
  path: D:/data/file

host:
  uri: http://localhost:${server.port}