#dev 开发环境
#pro 生产环境
spring:
  application:
    name: service-file
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      maxRequestSize: 1000MB
      
#system
server:
  port: 1001
  tomcat:
    basedir: /data/verify/temp/

#logback
logging:
  config: classpath:config/logback-spring.xml

#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml



